import type { SourceMention } from '../types';

export function collectBlogMentions(): SourceMention[] {
  const source_type = 'editorial' as const;

  return [
    { venue_name: 'Tres Monos', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source: 'Bars for Kings', source_type, source_url: 'https://barsforkings.com/blog/best-cocktail-bars-buenos-aires-2026/', context: 'Cocktail bar guide candidate.', rank_position: 1 },
    { venue_name: 'Aldos', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source: 'Bars for Kings', source_type, source_url: 'https://barsforkings.com/blog/best-cocktail-bars-buenos-aires-2026/', context: 'Wine-and-cocktail guide candidate in San Telmo.', rank_position: 2 },
    { venue_name: 'Vico Wine Bar', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'wine_bar', source: 'Bars for Kings', source_type, source_url: 'https://barsforkings.com/blog/best-bars-palermo-buenos-aires/', context: 'Palermo wine bar candidate.', rank_position: 3 },
    { venue_name: 'Floreria Atlantico', city: 'Buenos Aires', district: 'Retiro', category: 'cocktail_bar', source: 'Bars for Kings', source_type, source_url: 'https://barsforkings.com/blog/best-bars-palermo-buenos-aires/', context: 'Cocktail capital reference candidate.', rank_position: 4 },
    { venue_name: 'Cochinchina', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'cocktail_bar', source: 'Sherpa Food Tours', source_type, source_url: 'https://www.sherpafoodtours.com/buenos-aires-best-cocktail-bars-a-neighbourhood-guide/', context: 'Neighborhood cocktail guide candidate.', rank_position: 5 },
    { venue_name: 'Doppelganger Bar', city: 'Buenos Aires', district: 'San Telmo', category: 'cocktail_bar', source: 'Sherpa Food Tours', source_type, source_url: 'https://www.sherpafoodtours.com/buenos-aires-best-cocktail-bars-a-neighbourhood-guide/', context: 'San Telmo cocktail guide candidate.', rank_position: 6 },
    { venue_name: 'Rey de Copas', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source: 'Sherpa Food Tours', source_type, source_url: 'https://www.sherpafoodtours.com/buenos-aires-best-cocktail-bars-a-neighbourhood-guide/', context: 'Palermo cocktail guide candidate.', rank_position: 7 },
    { venue_name: 'Nicky Harrison', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source: 'Sherpa Food Tours', source_type, source_url: 'https://www.sherpafoodtours.com/buenos-aires-best-cocktail-bars-a-neighbourhood-guide/', context: 'Speakeasy-style cocktail candidate.', rank_position: 8 },
    { venue_name: 'Verne Club', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source: 'Marriott Bonvoy Traveler', source_type, source_url: 'https://traveler.marriott.com/buenos-aires/best-buenos-aires-bars/', context: 'Palermo cocktail guide candidate.', rank_position: 9 },
    { venue_name: 'La Fuerza', city: 'Buenos Aires', district: 'Chacarita', category: 'cocktail_bar', source: 'Marriott Bonvoy Traveler', source_type, source_url: 'https://traveler.marriott.com/buenos-aires/best-buenos-aires-bars/', context: 'Vermouth bar candidate.', rank_position: 10 },
    { venue_name: 'Napoles', city: 'Buenos Aires', district: 'San Telmo', category: 'cocktail_bar', source: 'Rough Guides', source_type, source_url: 'https://www.roughguides.com/argentina/best-bars-buenos-aires/', context: 'Visually distinctive bar candidate.', rank_position: 11 },
    { venue_name: 'On Tap', city: 'Buenos Aires', district: 'Colegiales', category: 'cocktail_bar', source: 'Rough Guides', source_type, source_url: 'https://www.roughguides.com/argentina/best-bars-buenos-aires/', context: 'Craft beer/social bar candidate requiring review.', rank_position: 12 },
    { venue_name: 'Overo Bar de Copas', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'wine_bar', source: 'View Buenos Aires', source_type, source_url: 'https://viewbuenosaires.com/wine-bars-buenos-aires/', context: 'Wine bar guide candidate.', rank_position: 13 },
    { venue_name: 'Trova Bar', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source: 'View Buenos Aires', source_type, source_url: 'https://viewbuenosaires.com/wine-bars-buenos-aires/', context: 'Palermo wine bar candidate.', rank_position: 14 },
    { venue_name: 'Pain et Vin', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source: 'View Buenos Aires', source_type, source_url: 'https://viewbuenosaires.com/wine-bars-buenos-aires/', context: 'Wine bar candidate.', rank_position: 15 },
    { venue_name: 'La Malbequeria', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source: 'View Buenos Aires', source_type, source_url: 'https://viewbuenosaires.com/wine-bars-buenos-aires/', context: 'Wine bar candidate.', rank_position: 16 },
    { venue_name: 'Ser y Tiempo', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source: 'Local Wine Guide', source_type, source_url: 'https://visitbue.com/guias/GUIA_GASTRONOMICA_BUE_eng.pdf', context: 'San Telmo wine candidate from city gastronomic guide context.', rank_position: 17 },
    { venue_name: 'Vina de San Telmo', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source: 'Visit BUE', source_type, source_url: 'https://visitbue.com/guias/GUIA_GASTRONOMICA_BUE_eng.pdf', context: 'San Telmo wine candidate.', rank_position: 18 },
    { venue_name: 'Confiteria La Ideal', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Historic cafe and salon candidate.', rank_position: 19 },
    { venue_name: 'Cafe Tortoni', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Historic cafe candidate requiring atmosphere review.', rank_position: 20 },
    { venue_name: 'La Biela', city: 'Buenos Aires', district: 'Recoleta', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Classic Recoleta cafe candidate.', rank_position: 21 },
    { venue_name: 'Cafe Rivas', city: 'Buenos Aires', district: 'San Telmo', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'San Telmo cafe candidate.', rank_position: 22 },
    { venue_name: 'Bar El Federal', city: 'Buenos Aires', district: 'San Telmo', category: 'restaurant', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Historic bar notable candidate.', rank_position: 23 },
    { venue_name: 'Los Galgos', city: 'Buenos Aires', district: 'Microcentro', category: 'restaurant', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Historic bar and restaurant candidate.', rank_position: 24 },
    { venue_name: 'El Cuartito', city: 'Buenos Aires', district: 'Recoleta', category: 'restaurant', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Classic pizzeria candidate requiring category review.', rank_position: 25 },
    { venue_name: 'Guerrin', city: 'Buenos Aires', district: 'Microcentro', category: 'restaurant', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Classic pizzeria candidate requiring atmosphere review.', rank_position: 26 },
    { venue_name: 'San Juanino', city: 'Buenos Aires', district: 'Recoleta', category: 'restaurant', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Traditional restaurant candidate.', rank_position: 27 },
    { venue_name: 'Reliquia', city: 'Buenos Aires', district: 'Villa Crespo', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Modern restaurant candidate.', rank_position: 28 },
    { venue_name: 'Mengano', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Restaurant candidate with local cuisine identity.', rank_position: 29 },
    { venue_name: 'La Alacena', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Pasta and neighborhood restaurant candidate.', rank_position: 30 },
    { venue_name: 'Corte Comedor', city: 'Buenos Aires', district: 'Belgrano', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Belgrano restaurant candidate.', rank_position: 31 },
    { venue_name: 'Narda Comedor', city: 'Buenos Aires', district: 'Belgrano', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Belgrano restaurant candidate.', rank_position: 32 },
    { venue_name: 'Apu Nena', city: 'Buenos Aires', district: 'Chacarita', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Chacarita restaurant candidate.', rank_position: 33 },
    { venue_name: 'Condarco', city: 'Buenos Aires', district: 'Chacarita', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Chacarita restaurant candidate.', rank_position: 34 },
    { venue_name: 'Sacro', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Design-forward restaurant candidate also found in local food guides.', rank_position: 35 },
    { venue_name: 'Anchoita', city: 'Buenos Aires', district: 'Chacarita', category: 'restaurant', source: 'Local Restaurant Guide', source_type, source_url: 'https://www.eater.com/maps/best-buenos-aires-restaurants-argentina', context: 'Restaurant candidate linked to wine/provisions ecosystem.', rank_position: 36 },
    { venue_name: 'Cafe Cuervo Palermo', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source: 'Specialty Coffee Blog', source_type, source_url: 'https://perfectdailygrind.com/', context: 'Alias-style specialty coffee mention for Cuervo Cafe.', rank_position: 37 },
    { venue_name: 'Lattente Coffee', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source: 'Specialty Coffee Blog', source_type, source_url: 'https://perfectdailygrind.com/', context: 'Alias-style specialty coffee mention for Lattente.', rank_position: 38 },
    { venue_name: 'Negro Cueva', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source: 'Specialty Coffee Blog', source_type, source_url: 'https://perfectdailygrind.com/', context: 'Alias mention for Negro Cueva de Cafe.', rank_position: 39 },
    { venue_name: 'La Kitchen', city: 'Buenos Aires', district: 'Retiro', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Retiro cafe candidate requiring review.', rank_position: 40 },
    { venue_name: 'Florida Garden', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source: 'Local Guide', source_type, source_url: 'https://turismo.buenosaires.gob.ar/', context: 'Classic downtown cafe candidate.', rank_position: 41 }
  ];
}
