import type { DiscoveryCategory, SourceMention, SourceType } from '../types';

type SourceKey =
  | 'tripadvisor'
  | 'culturetrip'
  | 'secret_buenos_aires'
  | 'visit_buenos_aires'
  | 'michelin'
  | 'worlds_best_bars'
  | '50best_discovery';

type VenueSeed = {
  name: string;
  district: string;
  category: DiscoveryCategory;
  context: string;
  sources: SourceKey[];
};

const SOURCE_CONFIG: Record<SourceKey, { source: string; source_type: SourceType; source_url: string }> = {
  tripadvisor: {
    source: 'Tripadvisor',
    source_type: 'community',
    source_url: 'https://www.tripadvisor.com/Restaurants-g312741-Buenos_Aires_Capital_Federal_District.html',
  },
  culturetrip: {
    source: 'Culture Trip',
    source_type: 'editorial',
    source_url: 'https://theculturetrip.com/south-america/argentina/articles/the-best-restaurants-in-buenos-aires',
  },
  secret_buenos_aires: {
    source: 'Secret Buenos Aires',
    source_type: 'editorial',
    source_url: 'https://secretbuenosaires.com/',
  },
  visit_buenos_aires: {
    source: 'Visit Buenos Aires',
    source_type: 'editorial',
    source_url: 'https://turismo.buenosaires.gob.ar/',
  },
  michelin: {
    source: 'Michelin',
    source_type: 'editorial',
    source_url: 'https://guide.michelin.com/ar/en/buenos-aires-region/buenos-aires/restaurants',
  },
  worlds_best_bars: {
    source: "World's Best Bars",
    source_type: 'editorial',
    source_url: 'https://www.worlds50bestbars.com/',
  },
  '50best_discovery': {
    source: '50 Best Discovery',
    source_type: 'editorial',
    source_url: 'https://www.theworlds50best.com/discovery/',
  },
};

const VENUES: VenueSeed[] = [
  { name: 'Cuervo Cafe', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee with repeat local and editorial visibility', sources: ['tripadvisor', 'culturetrip', 'secret_buenos_aires', 'visit_buenos_aires'] },
  { name: 'LAB Tostadores de Cafe', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee roaster repeatedly recommended for Palermo', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Lattente', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee cafe with strong Palermo recognition', sources: ['tripadvisor', 'culturetrip', 'secret_buenos_aires'] },
  { name: 'Vive Cafe', district: 'Palermo Soho', category: 'cafe', context: 'Colombian specialty coffee candidate with stay potential', sources: ['tripadvisor', 'culturetrip', 'secret_buenos_aires'] },
  { name: 'Full City Coffee House', district: 'Palermo Soho', category: 'cafe', context: 'coffee house candidate with community and guide mentions', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'RITA Specialty Coffee', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee candidate requiring seating review', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Gramo Cafe', district: 'Palermo Soho', category: 'cafe', context: 'coffee candidate with local community signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Lateral Cafe', district: 'Palermo Soho', category: 'cafe', context: 'Palermo coffee candidate from local lists', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Meme Cafe', district: 'Palermo Soho', category: 'cafe', context: 'Palermo coffee candidate requiring atmosphere validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Noire', district: 'Palermo Soho', category: 'cafe', context: 'Palermo coffee candidate with neighborhood signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Surry Hills Coffee', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee candidate with Palermo relevance', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'La Ventana Cafe', district: 'Palermo Soho', category: 'cafe', context: 'coffee and food candidate with local discovery signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Cafe Registrado', district: 'Palermo Soho', category: 'cafe', context: 'specialty coffee candidate with broader city visibility', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Birkin Coffee Bar', district: 'Palermo Soho', category: 'cafe', context: 'brunch and cafe candidate with Palermo guide visibility', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Ninina', district: 'Palermo Soho', category: 'cafe', context: 'bakery-cafe and brunch candidate requiring chain review', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Casa Dingo', district: 'Palermo Soho', category: 'cafe', context: 'Palermo cafe candidate with creative district relevance', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Cocu Boulangerie', district: 'Palermo Soho', category: 'cafe', context: 'bakery-cafe candidate requiring stay and atmosphere review', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Oli Cafe', district: 'Colegiales', category: 'cafe', context: 'Colegiales cafe and brunch candidate', sources: ['tripadvisor', 'secret_buenos_aires', 'visit_buenos_aires'] },
  { name: 'Altar Cafe', district: 'Colegiales', category: 'cafe', context: 'Colegiales specialty coffee candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Maleza Cafe', district: 'Colegiales', category: 'cafe', context: 'neighborhood cafe candidate for underrepresented Colegiales coverage', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Cafe Crespin', district: 'Villa Crespo', category: 'cafe', context: 'Villa Crespo neighborhood cafe candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Malvon', district: 'Villa Crespo', category: 'cafe', context: 'brunch cafe with neighborhood recognition', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Salvaje Bakery', district: 'Villa Crespo', category: 'cafe', context: 'bakery-cafe with strong design and local signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Kitchen', district: 'Retiro', category: 'cafe', context: 'Retiro cafe candidate for central coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Florida Garden', district: 'Microcentro', category: 'cafe', context: 'classic downtown cafe candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Cafe Tortoni', district: 'Microcentro', category: 'cafe', context: 'heritage cafe with high tourist and landmark signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Confiteria La Ideal', district: 'Microcentro', category: 'cafe', context: 'restored historic cafe and salon candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Confiteria Las Violetas', district: 'Microcentro', category: 'cafe', context: 'heritage cafe candidate with landmark signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'London City', district: 'Microcentro', category: 'cafe', context: 'classic cafe candidate with tourist signal', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Biela', district: 'Recoleta', category: 'cafe', context: 'classic Recoleta cafe with heritage and tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Blanca Deco and Cafe', district: 'Recoleta', category: 'cafe', context: 'Recoleta cafe candidate with design signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'L Harmonie', district: 'Recoleta', category: 'cafe', context: 'Recoleta coffee candidate from community recommendations', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Tea Connection Recoleta', district: 'Recoleta', category: 'cafe', context: 'Recoleta cafe candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'OSS Kafe', district: 'Belgrano', category: 'cafe', context: 'Belgrano specialty coffee candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Jaramillo Cafe', district: 'Belgrano', category: 'cafe', context: 'Belgrano coffee candidate with community signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Canillita Cafe', district: 'Belgrano', category: 'cafe', context: 'Belgrano coffee candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Amarante Cafe', district: 'Belgrano', category: 'cafe', context: 'Belgrano cafe candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Panera Rosa Belgrano', district: 'Belgrano', category: 'cafe', context: 'brunch chain candidate requiring rejection review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Le Ble Las Canitas', district: 'Las Canitas', category: 'cafe', context: 'Las Canitas cafe candidate for missing district coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Moshu Las Canitas', district: 'Las Canitas', category: 'cafe', context: 'Las Canitas brunch and cafe candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Cafe Rivas', district: 'San Telmo', category: 'cafe', context: 'San Telmo cafe candidate with historic neighborhood relevance', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'La Garage', district: 'San Telmo', category: 'cafe', context: 'San Telmo pastry and cafe candidate requiring atmosphere review', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Hierbabuena', district: 'San Telmo', category: 'cafe', context: 'San Telmo cafe and restaurant candidate with local guide signal', sources: ['tripadvisor', 'culturetrip'] },

  { name: 'Don Julio Parrilla', district: 'Palermo Soho', category: 'restaurant', context: 'high-recognition grill with repeated editorial visibility', sources: ['tripadvisor', 'michelin', '50best_discovery', 'culturetrip'] },
  { name: 'El Preferido de Palermo', district: 'Palermo Soho', category: 'restaurant', context: 'heritage-informed Palermo restaurant with repeat recommendations', sources: ['tripadvisor', 'michelin', '50best_discovery', 'culturetrip'] },
  { name: 'Gran Dabbang', district: 'Palermo Soho', category: 'restaurant', context: 'creative restaurant with strong local and editorial signal', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Nino Gordo', district: 'Palermo Soho', category: 'restaurant', context: 'high-energy restaurant with strong Palermo identity', sources: ['tripadvisor', '50best_discovery', 'culturetrip'] },
  { name: 'Proper', district: 'Palermo Soho', category: 'restaurant', context: 'atmospheric restaurant with editorial visibility', sources: ['tripadvisor', '50best_discovery', 'culturetrip'] },
  { name: 'La Carniceria', district: 'Palermo Soho', category: 'restaurant', context: 'compact grill restaurant with distinctive identity', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Mishiguene', district: 'Palermo Soho', category: 'restaurant', context: 'distinctive restaurant with high guide visibility', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'La Cabrera', district: 'Palermo Soho', category: 'restaurant', context: 'popular grill candidate with tourist and editorial signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Fogon Asado', district: 'Palermo Soho', category: 'restaurant', context: 'asado experience candidate with travel and guide mentions', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Mengano', district: 'Palermo Soho', category: 'restaurant', context: 'modern Argentine restaurant candidate', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Sacro', district: 'Palermo Hollywood', category: 'restaurant', context: 'design-forward restaurant candidate', sources: ['tripadvisor', '50best_discovery', 'culturetrip'] },
  { name: 'La Alacena', district: 'Palermo Hollywood', category: 'restaurant', context: 'neighborhood pasta restaurant candidate', sources: ['tripadvisor', 'michelin', 'culturetrip'] },
  { name: 'La Mar', district: 'Palermo Hollywood', category: 'restaurant', context: 'restaurant with strong atmosphere and guide signal', sources: ['tripadvisor', '50best_discovery', 'culturetrip'] },
  { name: 'Casa Cruz', district: 'Palermo Hollywood', category: 'restaurant', context: 'dining and nightlife candidate with polished atmosphere', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Chila', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero fine dining candidate with waterfront district relevance', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Cabaña Las Lilas', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero waterfront grill with high tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Happening Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'waterfront restaurant candidate for missing district coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Sottovoce Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Parolaccia Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero restaurant candidate requiring chain review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Marcelo', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero Italian restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Osaka Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero dining candidate with polished atmosphere', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Elena', district: 'Retiro', category: 'restaurant', context: 'hotel restaurant with polished dining atmosphere', sources: ['tripadvisor', 'michelin', '50best_discovery', 'culturetrip'] },
  { name: 'Dada Bistro', district: 'Retiro', category: 'restaurant', context: 'Retiro bistro candidate with local signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Basa Bar', district: 'Retiro', category: 'restaurant', context: 'Retiro restaurant and bar candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Aramburu', district: 'Recoleta', category: 'restaurant', context: 'fine dining candidate with strong editorial visibility', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Roux', district: 'Recoleta', category: 'restaurant', context: 'Recoleta restaurant candidate with guide visibility', sources: ['tripadvisor', 'michelin', 'culturetrip'] },
  { name: 'Fervor', district: 'Recoleta', category: 'restaurant', context: 'classic Recoleta dining candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'El Cuartito', district: 'Recoleta', category: 'restaurant', context: 'classic pizzeria with strong heritage and tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'San Juanino', district: 'Recoleta', category: 'restaurant', context: 'traditional restaurant candidate with local guide signal', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Casa Cavia', district: 'Palermo Chico', category: 'restaurant', context: 'design-led restaurant and garden setting candidate', sources: ['tripadvisor', '50best_discovery', 'culturetrip'] },
  { name: 'Corte Comedor', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate with guide visibility', sources: ['tripadvisor', 'michelin', 'culturetrip'] },
  { name: 'Narda Comedor', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Jolie Bistro', district: 'Belgrano', category: 'restaurant', context: 'Belgrano neighborhood restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Sucre', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate with polished atmosphere', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Anafe', district: 'Colegiales', category: 'restaurant', context: 'creative neighborhood restaurant candidate', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Cucina Paradiso Colegiales', district: 'Colegiales', category: 'restaurant', context: 'Colegiales restaurant candidate requiring chain review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Apu Nena', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant candidate with independent signal', sources: ['tripadvisor', 'michelin', 'culturetrip'] },
  { name: 'Condarco', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Anchoita', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant connected to wine and provisions ecosystem', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Acido', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant candidate with local community signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Mezzetta', district: 'Chacarita', category: 'restaurant', context: 'classic casual food candidate requiring atmosphere review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Chui', district: 'Villa Crespo', category: 'restaurant', context: 'plant-forward restaurant with strong setting and local following', sources: ['tripadvisor', 'michelin', '50best_discovery', 'culturetrip'] },
  { name: 'Julia', district: 'Villa Crespo', category: 'restaurant', context: 'small-format restaurant with tasting-menu identity', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Reliquia', district: 'Villa Crespo', category: 'restaurant', context: 'modern restaurant candidate', sources: ['tripadvisor', 'michelin', 'culturetrip'] },
  { name: 'Picaron', district: 'Villa Crespo', category: 'restaurant', context: 'Villa Crespo restaurant candidate with local signal', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Madre Rojas', district: 'Villa Crespo', category: 'restaurant', context: 'Villa Crespo restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Sarkis', district: 'Villa Crespo', category: 'restaurant', context: 'community-recommended restaurant candidate with high popularity', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Cafe San Juan', district: 'San Telmo', category: 'restaurant', context: 'San Telmo restaurant candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Bar El Federal', district: 'San Telmo', category: 'restaurant', context: 'historic San Telmo bar and restaurant candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Bar Britanico', district: 'San Telmo', category: 'restaurant', context: 'historic San Telmo cafe-bar candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Brigada', district: 'San Telmo', category: 'restaurant', context: 'San Telmo grill candidate with tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Aurelia', district: 'San Telmo', category: 'restaurant', context: 'San Telmo food community candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Napoles', district: 'San Telmo', category: 'restaurant', context: 'visually distinctive San Telmo venue candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Los Galgos', district: 'Microcentro', category: 'restaurant', context: 'historic bar and restaurant candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Guerrin', district: 'Microcentro', category: 'restaurant', context: 'classic pizzeria with heritage and tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Ajo Negro', district: 'Microcentro', category: 'restaurant', context: 'central restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Kansas Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant candidate requiring generic/chain review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Guitarrita Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas casual restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'SushiClub Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant candidate requiring chain review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Las Cholas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas parrilla candidate', sources: ['tripadvisor', 'culturetrip'] },

  { name: 'Pain et Vin', district: 'Palermo Soho', category: 'wine_bar', context: 'wine-focused Palermo candidate', sources: ['tripadvisor', 'culturetrip', '50best_discovery'] },
  { name: 'Vico Wine Bar', district: 'Palermo Hollywood', category: 'wine_bar', context: 'Palermo wine bar candidate with repeat guide visibility', sources: ['tripadvisor', 'culturetrip', '50best_discovery'] },
  { name: 'Aldos', district: 'San Telmo', category: 'wine_bar', context: 'restaurant and wine bar with strong guide visibility', sources: ['tripadvisor', 'michelin', '50best_discovery', 'culturetrip'] },
  { name: 'Naranjo Bar', district: 'Chacarita', category: 'wine_bar', context: 'natural wine and small plates candidate', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Anchoita Cava', district: 'Chacarita', category: 'wine_bar', context: 'wine and provisions candidate with strong editorial pull', sources: ['tripadvisor', 'michelin', '50best_discovery'] },
  { name: 'Ser y Tiempo', district: 'San Telmo', category: 'wine_bar', context: 'San Telmo wine candidate with local signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Vini Bar', district: 'Villa Crespo', category: 'wine_bar', context: 'Villa Crespo wine bar candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Trova Bar', district: 'Palermo Soho', category: 'wine_bar', context: 'Palermo wine candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Overo Bar de Copas', district: 'Palermo Hollywood', category: 'wine_bar', context: 'wine bar candidate with Palermo context', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'La Malbequeria', district: 'Palermo Soho', category: 'wine_bar', context: 'Malbec-focused wine candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Vina de San Telmo', district: 'San Telmo', category: 'wine_bar', context: 'San Telmo wine candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Gran Bar Danzon', district: 'Recoleta', category: 'wine_bar', context: 'Recoleta wine and cocktail candidate', sources: ['tripadvisor', 'culturetrip', '50best_discovery'] },
  { name: 'Nilson', district: 'Recoleta', category: 'wine_bar', context: 'Recoleta wine candidate requiring review', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Hache Almacen', district: 'Villa Crespo', category: 'wine_bar', context: 'Villa Crespo wine and small plates candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Uva', district: 'Chacarita', category: 'wine_bar', context: 'Chacarita wine candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Diviiino', district: 'Palermo Soho', category: 'wine_bar', context: 'Palermo wine candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Finde', district: 'Colegiales', category: 'wine_bar', context: 'Colegiales wine candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Aldo Vinoteca Recoleta', district: 'Recoleta', category: 'wine_bar', context: 'Recoleta wine retail and tasting candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Bodega Amparo', district: 'Puerto Madero', category: 'wine_bar', context: 'Puerto Madero wine candidate for missing district coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Wine Bar Puerto Cristal', district: 'Puerto Madero', category: 'wine_bar', context: 'Puerto Madero wine candidate requiring validation', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Cava de Vittorio', district: 'Las Canitas', category: 'wine_bar', context: 'Las Canitas wine candidate for district coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Las Canitas Wine Bar', district: 'Las Canitas', category: 'wine_bar', context: 'Las Canitas wine candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'Tres Monos', district: 'Palermo Soho', category: 'cocktail_bar', context: 'cocktail bar with strong international recognition', sources: ['tripadvisor', 'worlds_best_bars', '50best_discovery', 'culturetrip'] },
  { name: 'Floreria Atlantico', district: 'Retiro', category: 'cocktail_bar', context: 'signature Buenos Aires cocktail bar candidate', sources: ['tripadvisor', 'worlds_best_bars', '50best_discovery', 'culturetrip'] },
  { name: 'Presidente Bar', district: 'Recoleta', category: 'cocktail_bar', context: 'Recoleta cocktail candidate with polished atmosphere', sources: ['tripadvisor', 'worlds_best_bars', '50best_discovery'] },
  { name: 'Cochinchina', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'cocktail bar with high guide visibility', sources: ['tripadvisor', 'worlds_best_bars', '50best_discovery'] },
  { name: 'Doppelganger Bar', district: 'San Telmo', category: 'cocktail_bar', context: 'San Telmo cocktail candidate', sources: ['tripadvisor', 'worlds_best_bars', 'culturetrip'] },
  { name: 'La Fuerza', district: 'Chacarita', category: 'cocktail_bar', context: 'vermouth bar and social drinking candidate', sources: ['tripadvisor', 'worlds_best_bars', '50best_discovery', 'culturetrip'] },
  { name: 'Verne Club', district: 'Palermo Soho', category: 'cocktail_bar', context: 'Palermo cocktail candidate', sources: ['tripadvisor', 'worlds_best_bars', 'culturetrip'] },
  { name: 'Uptown', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'high-concept cocktail bar candidate', sources: ['tripadvisor', 'worlds_best_bars', 'culturetrip'] },
  { name: '878 Bar', district: 'Villa Crespo', category: 'cocktail_bar', context: 'long-running cocktail bar candidate', sources: ['tripadvisor', 'worlds_best_bars', 'culturetrip'] },
  { name: 'Rey de Copas', district: 'Palermo Soho', category: 'cocktail_bar', context: 'Palermo cocktail guide candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Nicky Harrison', district: 'Palermo Soho', category: 'cocktail_bar', context: 'speakeasy-style cocktail candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Frank’s', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'speakeasy cocktail candidate', sources: ['tripadvisor', 'worlds_best_bars'] },
  { name: 'Victoria Brown', district: 'Palermo Soho', category: 'cocktail_bar', context: 'cocktail bar candidate with design signal', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Trade Sky Bar', district: 'Retiro', category: 'cocktail_bar', context: 'sky bar candidate with view and tourist signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Pony Line', district: 'Retiro', category: 'cocktail_bar', context: 'hotel cocktail bar candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Crystal Bar', district: 'Retiro', category: 'cocktail_bar', context: 'hotel bar candidate with skyline view signal', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Puerta Uno', district: 'Belgrano', category: 'cocktail_bar', context: 'Belgrano cocktail candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Mixtape Bar', district: 'Chacarita', category: 'cocktail_bar', context: 'Chacarita bar candidate with local community signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Bierlife', district: 'San Telmo', category: 'cocktail_bar', context: 'craft beer and social bar candidate requiring category review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'The Hole Bar', district: 'Palermo Soho', category: 'cocktail_bar', context: 'themed cocktail candidate requiring atmosphere review', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Avant Garten', district: 'Palermo Soho', category: 'cocktail_bar', context: 'outdoor bar candidate requiring generic nightlife review', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Mamba Bar', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'Palermo Hollywood cocktail candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Oh No Lulu', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'cocktail and nightlife candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Rooftop Puerto Madero', district: 'Puerto Madero', category: 'cocktail_bar', context: 'Puerto Madero cocktail candidate with view signal requiring validation', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'The Library Lounge', district: 'Recoleta', category: 'cocktail_bar', context: 'hotel lounge candidate with polished atmosphere', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Danzon Bar', district: 'Recoleta', category: 'cocktail_bar', context: 'Recoleta cocktail and wine candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Las Canitas Cocktail Club', district: 'Las Canitas', category: 'cocktail_bar', context: 'Las Canitas cocktail candidate for missing district coverage', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Club de la Birra Las Canitas', district: 'Las Canitas', category: 'cocktail_bar', context: 'Las Canitas social bar candidate requiring category review', sources: ['tripadvisor', 'visit_buenos_aires'] },

  { name: 'Tostado Puerto Madero', district: 'Puerto Madero', category: 'cafe', context: 'Puerto Madero cafe candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Ol Dias Puerto Madero', district: 'Puerto Madero', category: 'cafe', context: 'Puerto Madero cafe candidate for waterfront district coverage', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Le Pain Quotidien Puerto Madero', district: 'Puerto Madero', category: 'cafe', context: 'Puerto Madero cafe candidate requiring chain review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Freddo Puerto Madero Cafe', district: 'Puerto Madero', category: 'cafe', context: 'Puerto Madero cafe listing likely unsuitable for Korantis', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Panera Rosa Puerto Madero', district: 'Puerto Madero', category: 'cafe', context: 'Puerto Madero brunch chain candidate requiring rejection review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Bistecca Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero restaurant candidate for district coverage', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Cabaña Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero grill candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Riviere Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero waterfront restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Sorrento Puerto Madero', district: 'Puerto Madero', category: 'restaurant', context: 'Puerto Madero restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Madero Tango Restaurant', district: 'Puerto Madero', category: 'restaurant', context: 'tourist-heavy Puerto Madero dinner candidate requiring rejection review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'The Library Lounge Puerto Madero', district: 'Puerto Madero', category: 'cocktail_bar', context: 'Puerto Madero lounge candidate with hotel/bar signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Madero Harbour Bar', district: 'Puerto Madero', category: 'cocktail_bar', context: 'Puerto Madero waterfront bar candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },

  { name: 'Voulez Bar', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant and brunch candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Olsen Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant candidate requiring current-status review', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Mott Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Novecento Las Canitas', district: 'Las Canitas', category: 'restaurant', context: 'Las Canitas restaurant candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Tea Connection Las Canitas', district: 'Las Canitas', category: 'cafe', context: 'Las Canitas cafe candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Decata Las Canitas', district: 'Las Canitas', category: 'wine_bar', context: 'Las Canitas wine candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Calle Bar Las Canitas', district: 'Las Canitas', category: 'cocktail_bar', context: 'Las Canitas cocktail candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Boticario Las Canitas', district: 'Las Canitas', category: 'cocktail_bar', context: 'Las Canitas bar candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'La Ferneteria', district: 'Colegiales', category: 'cocktail_bar', context: 'Colegiales cocktail and social bar candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Mercado de Pulgas Cafe', district: 'Colegiales', category: 'cafe', context: 'Colegiales cafe candidate tied to design district context', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Narda Lepes Mercado', district: 'Colegiales', category: 'restaurant', context: 'Colegiales food-market candidate requiring venue validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Ruda Cocina', district: 'Colegiales', category: 'restaurant', context: 'Colegiales neighborhood restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Marti Barra', district: 'Colegiales', category: 'wine_bar', context: 'Colegiales wine and small plates candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Bar Roma Colegiales', district: 'Colegiales', category: 'cocktail_bar', context: 'Colegiales bar candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'Hache Palermo', district: 'Palermo Hollywood', category: 'wine_bar', context: 'Palermo Hollywood wine candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Soria Bar', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'Palermo Hollywood cocktail bar candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'La Calle Bar Palermo', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'Palermo Hollywood cocktail candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'The Hole Palermo', district: 'Palermo Hollywood', category: 'cocktail_bar', context: 'Palermo cocktail candidate with themed design signal', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'La Dorita Palermo', district: 'Palermo Hollywood', category: 'restaurant', context: 'Palermo restaurant candidate requiring generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Casa Munay', district: 'Palermo Hollywood', category: 'restaurant', context: 'Palermo Hollywood restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'La Pescadorita', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Caseros Belgrano', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Belgrano Social Club', district: 'Belgrano', category: 'cocktail_bar', context: 'Belgrano cocktail/social candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Cava de Vittorio Belgrano', district: 'Belgrano', category: 'wine_bar', context: 'Belgrano wine candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Orno Belgrano', district: 'Belgrano', category: 'restaurant', context: 'Belgrano restaurant candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Mordisco Belgrano', district: 'Belgrano', category: 'cafe', context: 'Belgrano cafe candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'La Pecora Nera', district: 'Recoleta', category: 'restaurant', context: 'Recoleta restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Sottovoce Recoleta', district: 'Recoleta', category: 'restaurant', context: 'Recoleta restaurant candidate requiring chain/generic review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Milion', district: 'Recoleta', category: 'cocktail_bar', context: 'Recoleta mansion bar candidate with design signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'La Rambla Recoleta', district: 'Recoleta', category: 'restaurant', context: 'classic Recoleta restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Josephina Cafe', district: 'Recoleta', category: 'cafe', context: 'Recoleta cafe candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Clorindo Cafe', district: 'Recoleta', category: 'cafe', context: 'Recoleta cafe candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'Gran Cafe Tortoni Bar', district: 'Microcentro', category: 'cocktail_bar', context: 'heritage bar candidate with tourist signal', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: '36 Billares', district: 'Microcentro', category: 'restaurant', context: 'historic cafe-bar candidate with heritage signal', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Giralda', district: 'Microcentro', category: 'cafe', context: 'classic downtown cafe candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'El Gato Negro', district: 'Microcentro', category: 'cafe', context: 'historic spice-shop cafe candidate requiring seating review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Puerto Rico', district: 'Microcentro', category: 'cafe', context: 'notable historic cafe candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Academia', district: 'Microcentro', category: 'restaurant', context: 'classic downtown restaurant candidate', sources: ['tripadvisor', 'visit_buenos_aires'] },

  { name: 'Plaza Bar', district: 'Retiro', category: 'cocktail_bar', context: 'Retiro hotel bar candidate with heritage signal', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Arroyo Bar', district: 'Retiro', category: 'cocktail_bar', context: 'Retiro cocktail candidate near gallery district', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Farinelli Arroyo', district: 'Retiro', category: 'cafe', context: 'Retiro cafe candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Museo Fernandez Blanco Cafe', district: 'Retiro', category: 'cafe', context: 'Retiro cultural cafe candidate requiring validation', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Tancat', district: 'Retiro', category: 'restaurant', context: 'classic Retiro restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Filo', district: 'Retiro', category: 'restaurant', context: 'Retiro restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },

  { name: 'Desnivel', district: 'San Telmo', category: 'restaurant', context: 'San Telmo parrilla candidate with tourist signal', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'El Banco Rojo', district: 'San Telmo', category: 'restaurant', context: 'casual San Telmo candidate requiring atmosphere review', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Pulperia Quilapan', district: 'San Telmo', category: 'restaurant', context: 'heritage setting restaurant candidate', sources: ['tripadvisor', 'culturetrip', 'visit_buenos_aires'] },
  { name: 'Atis Bar', district: 'San Telmo', category: 'cocktail_bar', context: 'San Telmo courtyard bar candidate with atmosphere signal', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Gibraltar', district: 'San Telmo', category: 'cocktail_bar', context: 'San Telmo pub/bar candidate requiring category review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Mansion Boero Wine', district: 'San Telmo', category: 'wine_bar', context: 'San Telmo wine candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'La Fuerza Vermu Chacarita', district: 'Chacarita', category: 'cocktail_bar', context: 'alias-style vermouth mention for La Fuerza', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Sifon Soderia', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant/bar candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Nola Chacarita', district: 'Chacarita', category: 'restaurant', context: 'Chacarita restaurant candidate', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'El Galpon de Tacuara Chacarita', district: 'Chacarita', category: 'cocktail_bar', context: 'Chacarita social bar candidate requiring category review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'Cafe Mishiguene Chacarita', district: 'Chacarita', category: 'cafe', context: 'Chacarita cafe candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Noire Chacarita', district: 'Chacarita', category: 'cafe', context: 'Chacarita coffee candidate requiring branch review', sources: ['tripadvisor', 'secret_buenos_aires'] },

  { name: 'Growlers Villa Crespo', district: 'Villa Crespo', category: 'cocktail_bar', context: 'Villa Crespo social bar candidate requiring category review', sources: ['tripadvisor', 'visit_buenos_aires'] },
  { name: 'La Crespo', district: 'Villa Crespo', category: 'restaurant', context: 'Villa Crespo restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Siamo nel Forno', district: 'Villa Crespo', category: 'restaurant', context: 'Villa Crespo restaurant candidate', sources: ['tripadvisor', 'culturetrip'] },
  { name: 'Cafe Crespín Villa Crespo', district: 'Villa Crespo', category: 'cafe', context: 'alias-style neighborhood cafe mention', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'Morro Cafe', district: 'Villa Crespo', category: 'cafe', context: 'Villa Crespo cafe candidate requiring validation', sources: ['tripadvisor', 'secret_buenos_aires'] },
  { name: 'La Esperanza de los Ascurra', district: 'Villa Crespo', category: 'restaurant', context: 'Villa Crespo restaurant candidate with local signal', sources: ['tripadvisor', 'culturetrip'] }
];

export function collectExpandedMentions(sourceKey: SourceKey): SourceMention[] {
  const config = SOURCE_CONFIG[sourceKey];
  return VENUES
    .filter((venue) => venue.sources.includes(sourceKey))
    .map((venue, index) => ({
      venue_name: venue.name,
      city: 'Buenos Aires',
      district: venue.district,
      category: venue.category,
      source: config.source,
      source_type: config.source_type,
      source_url: config.source_url,
      context: venue.context,
      rank_position: index + 1,
    }));
}
