import type { SourceMention } from '../types';

export function collectTimeOutMentions(): SourceMention[] {
  const source = 'Time Out';
  const source_type = 'editorial' as const;

  return [
    { venue_name: 'Casa Dingo', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/es/buenos-aires/guia-time-out-buenos-aires-restaurantes-bares-cafeterias-2025', context: 'Featured cafe in the Time Out Buenos Aires food guide context.', rank_position: 1 },
    { venue_name: 'LAB Tostadores de Cafe', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Specialty coffee reference for Palermo discovery.', rank_position: 2 },
    { venue_name: 'Lattente', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Specialty coffee cafe frequently referenced in Palermo lists.', rank_position: 3 },
    { venue_name: 'Vive Cafe', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Colombian coffee cafe with sit-down appeal in Palermo.', rank_position: 4 },
    { venue_name: 'Cuervo Cafe', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Specialty coffee candidate with repeated local visibility.', rank_position: 5 },
    { venue_name: 'Oli Cafe', city: 'Buenos Aires', district: 'Colegiales', category: 'cafe', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Neighborhood cafe and brunch candidate.', rank_position: 6 },
    { venue_name: 'Don Julio Parrilla', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'High-recognition Buenos Aires restaurant candidate.', rank_position: 7 },
    { venue_name: 'El Preferido de Palermo', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Modern porteno restaurant with heritage identity.', rank_position: 8 },
    { venue_name: 'Gran Dabbang', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Creative restaurant frequently recommended for Buenos Aires dining.', rank_position: 9 },
    { venue_name: 'Chui', city: 'Buenos Aires', district: 'Villa Crespo', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Plant-forward restaurant with strong setting and local following.', rank_position: 10 },
    { venue_name: 'Nino Gordo', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'High-energy Palermo restaurant candidate.', rank_position: 11 },
    { venue_name: 'Proper', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Atmospheric restaurant candidate with repeated guide presence.', rank_position: 12 },
    { venue_name: 'La Carniceria', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Compact restaurant with strong grill identity.', rank_position: 13 },
    { venue_name: 'Sacro', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Design-forward restaurant candidate.', rank_position: 14 },
    { venue_name: 'Anafe', city: 'Buenos Aires', district: 'Colegiales', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Creative neighborhood restaurant candidate.', rank_position: 15 },
    { venue_name: 'Julia', city: 'Buenos Aires', district: 'Villa Crespo', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Small-format restaurant with tasting-menu identity.', rank_position: 16 },
    { venue_name: 'Aramburu', city: 'Buenos Aires', district: 'Recoleta', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Fine dining candidate with strong editorial visibility.', rank_position: 17 },
    { venue_name: 'Elena', city: 'Buenos Aires', district: 'Retiro', category: 'restaurant', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Hotel restaurant with polished dining atmosphere.', rank_position: 18 },
    { venue_name: 'Tres Monos', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Cocktail guide candidate for Palermo.', rank_position: 19 },
    { venue_name: 'Floreria Atlantico', city: 'Buenos Aires', district: 'Retiro', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Signature Buenos Aires cocktail bar candidate.', rank_position: 20 },
    { venue_name: 'Presidente Bar', city: 'Buenos Aires', district: 'Recoleta', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Recoleta cocktail candidate with polished atmosphere.', rank_position: 21 },
    { venue_name: 'Cochinchina', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Cocktail bar with high guide visibility.', rank_position: 22 },
    { venue_name: 'Doppelganger Bar', city: 'Buenos Aires', district: 'San Telmo', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'San Telmo cocktail candidate.', rank_position: 23 },
    { venue_name: 'La Fuerza', city: 'Buenos Aires', district: 'Chacarita', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Vermouth bar and social drinking candidate.', rank_position: 24 },
    { venue_name: 'Verne Club', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Palermo cocktail candidate.', rank_position: 25 },
    { venue_name: 'Uptown', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'High-concept cocktail bar candidate.', rank_position: 26 },
    { venue_name: '878 Bar', city: 'Buenos Aires', district: 'Villa Crespo', category: 'cocktail_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires/best-bars-buenos-aires-cocktail-guide-visit-bue-best-drinks', context: 'Long-running cocktail bar candidate.', rank_position: 27 },
    { venue_name: 'Vico Wine Bar', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'wine_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Wine bar candidate with strong Palermo visibility.', rank_position: 28 },
    { venue_name: 'Aldos', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Restaurant and wine bar candidate.', rank_position: 29 },
    { venue_name: 'Pain et Vin', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Wine-focused Palermo candidate.', rank_position: 30 },
    { venue_name: 'Naranjo Bar', city: 'Buenos Aires', district: 'Chacarita', category: 'wine_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Natural wine bar and restaurant candidate.', rank_position: 31 },
    { venue_name: 'Anchoita Cava', city: 'Buenos Aires', district: 'Chacarita', category: 'wine_bar', source, source_type, source_url: 'https://www.timeout.com/buenos-aires', context: 'Wine and provisions candidate with editorial pull.', rank_position: 32 }
  ];
}
