import type { SourceMention } from '../types';

export function collectWanderlogMentions(): SourceMention[] {
  const source = 'Wanderlog';
  const source_type = 'editorial' as const;
  const base = 'https://wanderlog.com/list/geoCategory/786403/best-wine-bars-and-tasting-rooms-in-buenos-aires';

  return [
    { venue_name: 'Overo Bar de Copas', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'wine_bar', source, source_type, source_url: base, context: 'Wanderlog wine bar list candidate with Palermo context.', rank_position: 1 },
    { venue_name: 'Aldos', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source, source_type, source_url: base, context: 'Wine bar and restaurant with repeated guide visibility.', rank_position: 2 },
    { venue_name: 'Vico Wine Bar', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'wine_bar', source, source_type, source_url: base, context: 'Palermo wine bar candidate.', rank_position: 3 },
    { venue_name: 'Pain et Vin', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source, source_type, source_url: base, context: 'Wine bar and tasting candidate.', rank_position: 4 },
    { venue_name: 'La Malbequeria', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source, source_type, source_url: base, context: 'Malbec-focused wine candidate.', rank_position: 5 },
    { venue_name: 'Naranjo Bar', city: 'Buenos Aires', district: 'Chacarita', category: 'wine_bar', source, source_type, source_url: base, context: 'Natural wine and small plates candidate.', rank_position: 6 },
    { venue_name: 'Anchoita Cava', city: 'Buenos Aires', district: 'Chacarita', category: 'wine_bar', source, source_type, source_url: base, context: 'Wine retail and tasting candidate with strong editorial fit.', rank_position: 7 },
    { venue_name: 'Ser y Tiempo', city: 'Buenos Aires', district: 'San Telmo', category: 'wine_bar', source, source_type, source_url: base, context: 'San Telmo wine candidate.', rank_position: 8 },
    { venue_name: 'Vini Bar', city: 'Buenos Aires', district: 'Villa Crespo', category: 'wine_bar', source, source_type, source_url: base, context: 'Villa Crespo wine bar candidate.', rank_position: 9 },
    { venue_name: 'Trova Bar', city: 'Buenos Aires', district: 'Palermo Soho', category: 'wine_bar', source, source_type, source_url: base, context: 'Palermo wine candidate.', rank_position: 10 },
    { venue_name: 'Don Julio Parrilla', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Restaurant list candidate.', rank_position: 11 },
    { venue_name: 'El Preferido de Palermo', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Restaurant list candidate.', rank_position: 12 },
    { venue_name: 'La Cabrera', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Grill restaurant with high tourist/editorial visibility.', rank_position: 13 },
    { venue_name: 'Mishiguene', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Restaurant candidate with distinctive culinary identity.', rank_position: 14 },
    { venue_name: 'Roux', city: 'Buenos Aires', district: 'Recoleta', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Recoleta restaurant candidate.', rank_position: 15 },
    { venue_name: 'Fervor', city: 'Buenos Aires', district: 'Recoleta', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Classic dining candidate.', rank_position: 16 },
    { venue_name: 'Cafe San Juan', city: 'Buenos Aires', district: 'San Telmo', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'San Telmo restaurant candidate.', rank_position: 17 },
    { venue_name: 'Bar El Federal', city: 'Buenos Aires', district: 'San Telmo', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Historic bar and restaurant candidate.', rank_position: 18 },
    { venue_name: 'Bar Britanico', city: 'Buenos Aires', district: 'San Telmo', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Historic San Telmo cafe-bar candidate.', rank_position: 19 },
    { venue_name: 'Fogon Asado', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Asado experience candidate.', rank_position: 20 },
    { venue_name: 'Gran Dabbang', city: 'Buenos Aires', district: 'Palermo Soho', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Creative restaurant candidate.', rank_position: 21 },
    { venue_name: 'Chui', city: 'Buenos Aires', district: 'Villa Crespo', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Plant-forward restaurant candidate.', rank_position: 22 },
    { venue_name: 'LAB Tostadores de Cafe', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Coffee shop list candidate.', rank_position: 23 },
    { venue_name: 'Full City Coffee House', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Specialty coffee candidate.', rank_position: 24 },
    { venue_name: 'Cuervo Cafe', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Coffee shop candidate.', rank_position: 25 },
    { venue_name: 'Negro Cueva de Cafe', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Central cafe candidate.', rank_position: 26 },
    { venue_name: 'Cafe Registrado', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Specialty coffee candidate.', rank_position: 27 },
    { venue_name: 'Birkin Coffee', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Cafe and brunch candidate.', rank_position: 28 },
    { venue_name: 'Pani', city: 'Buenos Aires', district: 'Recoleta', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Cafe and brunch candidate.', rank_position: 29 },
    { venue_name: 'Ninina', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Cafe and bakery candidate.', rank_position: 30 },
    { venue_name: 'Cocu Boulangerie', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Bakery-cafe candidate requiring editorial review.', rank_position: 31 },
    { venue_name: 'Oui Oui', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Cafe and brunch candidate.', rank_position: 32 },
    { venue_name: 'Confiteria Las Violetas', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Historic cafe candidate requiring editorial review.', rank_position: 33 },
    { venue_name: 'London City', city: 'Buenos Aires', district: 'Microcentro', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Historic cafe candidate requiring editorial review.', rank_position: 34 },
    { venue_name: 'La Panera Rosa', city: 'Buenos Aires', district: 'Palermo Soho', category: 'cafe', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/18317/best-coffee-shops-and-cafes-in-buenos-aires', context: 'Cafe/brunch candidate requiring chain review.', rank_position: 35 },
    { venue_name: 'Casa Cavia', city: 'Buenos Aires', district: 'Palermo Chico', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Design-led restaurant candidate.', rank_position: 36 },
    { venue_name: 'La Mar', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Restaurant candidate with strong ambiance.', rank_position: 37 },
    { venue_name: 'Casa Cruz', city: 'Buenos Aires', district: 'Palermo Hollywood', category: 'restaurant', source, source_type, source_url: 'https://wanderlog.com/list/geoCategory/20597/best-restaurants-in-buenos-aires', context: 'Dining and nightlife candidate.', rank_position: 38 }
  ];
}
